// Program.cs  –  ASP.NET Core Web API entry point
// Generated by: dotnet new webapi -controllers
// Updated with: CORS for local frontend + HttpClient for Anthropic API

var builder = WebApplication.CreateBuilder(args);

// ── 1. CORS ────────────────────────────────────────────────────────────────
// Allows your frontend (e.g. React / plain HTML) running on localhost
// to call this backend without browser "blocked by CORS policy" errors.
//
// For production, replace the origins below with your real domain(s).

const string CorsPolicyName = "LocalFrontend";

builder.Services.AddCors(options =>
{
    options.AddPolicy(CorsPolicyName, policy =>
    {
        policy
            // Add every local port your frontend might use
            .WithOrigins(
                "http://localhost:3000",   // React (CRA / Vite)
                "http://localhost:5173",   // Vite default
                "http://localhost:4200",   // Angular
                "http://localhost:8080",   // Vue CLI
                "http://127.0.0.1:5500",  // VS Code Live Server
                "http://localhost:5500"    // VS Code Live Server (alt)
            )
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

// ── 2. HttpClient (named) ──────────────────────────────────────────────────
// ChatController uses this named client to talk to the Anthropic API.
// Configuring it here lets ASP.NET manage connection pooling correctly.

builder.Services.AddHttpClient("GroqClient", client =>
{
    client.Timeout = TimeSpan.FromSeconds(30);
    client.DefaultRequestHeaders.Add("Accept", "application/json");
});

// ── 3. Controllers & Swagger ───────────────────────────────────────────────

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new() { Title = "AI Chatbot API", Version = "v1" });
});

// ── 4. Build & configure the HTTP pipeline ─────────────────────────────────

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

// IMPORTANT: UseCors must come BEFORE UseAuthorization and MapControllers
app.UseCors(CorsPolicyName);

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();

// ── Environment / configuration reminder ──────────────────────────────────
//
// Set your Gemini API key using ONE of these methods:
//
// Option A – environment variable (recommended for security):
//   Windows PowerShell:  $env:GEMINI_API_KEY = "sk-ant-..."
//   macOS / Linux:       export GEMINI_API_KEY="sk-ant-..."
//
// Option B – appsettings.Development.json (never commit to source control!):
//   {
//     "Gemini": {
//       "ApiKey": "sk-ant-..."
//     }
//   }
//
// Get your key at: https://console.anthropic.com